---
  - name: "Get rid of /home"
    mount:
      name: /home
      state: unmounted
  - name: "Get rid of /home from /etc/fstab"
    mount:
      name: /home
      state: absent
  - name: "Remove /home LV"
    lvol:
      vg: "rhel_{{ inventory_hostname_short }}"
      lv: home
      state: absent
      force: yes
...
