---
- hosts: satellite6
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - common
    - epel-not-present
    - rhsm
    - ntp
    ###- upgrade-restart
    ###- satellite-ec2-partitioning
    - remove-home-extend-root
    - setup
    - enlarge-arp-table
    - satellite-populate
    - client-content
...
